### ISSUE TITLE
rootMargin should allow 0 without units

### ISSUE THREAD

**Issue by cezaraugusto** [w3c/IntersectionObserver#244]
having to write `0px` or `0%` seems unnecessary and is error-prone for developers used to type this way with CSS margin shorthand.

related #126

**Comment by midzer** [comment]
`rootMargin` with `0` work for latest browsers.
Firefox 52 throwed a warning for me in this case. Thats why I've updated the docs https://github.com/w3c/IntersectionObserver/commit/22b8b74f2ab28959c088aabba80bb17cee0d72a4

**Comment by cezaraugusto** [comment]
are you talking about beta/nightly versions? 

```
new window.IntersectionObserver(() => {}, {rootMargin: 0})
```

* Chrome 60 _not working_
* Opera 47 _not working_
* Safari nor 10.1.2 _not working_

Worked only in FF 55.0.3. Well, I guess that's something browser vendors should take care and nothing from the spec to be done?

**Comment by rjgotten** [comment]
Can't believe that this is still a problem even now, with Chrome 73.
`rootMargin: "100px 0 0 0" continues to throw a SyntaxError which complains that values 'must be specified in pixels or percent'

**Comment by lebnic** [comment]
Still relevant, indeed `rootMargin: "100px 0 0 0"` or `rootMargin: "0"` or `rootMargin: "200px 0 0"` throws an error...

This is problematic, because documentation states that `Can have values similar to the CSS margin property,` (ref: https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API)

**Comment by pikeas** [comment]
Still happening as of April 2021. @lebnic is right, the rootMargin documentation says that it follows the syntax for margin, which means `0` should be a valid value.

**Comment by emilio** [comment]
Well, the documentation is not the spec. Spec is [here](https://w3c.github.io/IntersectionObserver/#parse-a-root-margin) and it doesn't do anything with `<number>` tokens, so zero is not allowed. That's not to say it couldn't be changed potentially, just that as things stand, the documentation is wrong and browsers are right.

**Comment by rjgotten** [comment]
As it stands even that official spec mentions that the `rootMargin` value is provided
> in a manner similar to CSS’s margin property

The problem is the spec declares `rootMargin` to be composed as a list of `<dimension>` values, when it should be composed of a list of `<length-percentage>` values, just like `margin` is. (And just like basically every other property that has to do with dimensionality or position is.)

Imho, this is spec-error that has trickled down to implementation error. As simple as that.

**Comment by emilio** [comment]
"similar to" is not quite a formal definition. It is a bit more complicated than just `<length-percentage>`, because at least as things stand, it's not clear what e.g. font-relative units would do. So you probably want something like `<length-percentage>`, but only allowing absolute lengths or percentages.

**Comment by wolfbeast** [comment]
This has my vote. Current implementations make and empty or whitespace string be equal to 0px, but "0" is not? That's madness.

**Comment by wolfbeast** [comment]
In anticipation of this spec error being resolved, I've adjusted the Goanna implementation to accept unitless values as it simply makes a lot more sense to have it aligned with `margin` and similar dimensional properties.

**Comment by miketaylr** [comment]
It makes sense to treat "0" as "0px", I think, somewhere around step 4 of https://w3c.github.io/IntersectionObserver/#parse-a-root-margin.
